version: '2'

volumes:
  volume_homeassistant:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /c/Users/Nathan/Development/balena-ha/homeassistant/config

services:

  homeassistant:
    build: 
      dockerfile: Dockerfile.development